### ISSUE TITLE
MC Server 1.16.4 - Can't move

### ISSUE THREAD

**Issue by MachinegunMarty** [ochotonida/curious-armor-stands#1]
Curious Armor Stands-1.16.3-2.0.0.jar
forge-1.16.4-35.0.7.jar

When i install it on my server and login, i can't move.
It also doesn't render my arm.
I can break blocks near me (without animation), but i don't fall down if i break the block under me.
So you just hang in the sky, unable to move.

I tried in a single player world and there everything works, just on server it doesn't.

grtz,

Machinegun Marty

**Comment by ochotonida** [comment]
Thanks for the report, uploading a patch right now

**Comment by ochotonida** [comment]
I managed to fix the bug, but realized that the mod still doesn't fully work properly on servers (equipping curios on armor stands doesn't actually work). After a lot of searching I found that this is very likely a bug with Curios rather than with this mod. I'll upload the patch anyways, but Curios will have to update first before it can be used on servers
